### ISSUE TITLE
ImportError when I try to run training

### ISSUE THREAD

**Issue by ericdai713** [WendongZh/SPL#6]
Hi, I got the following error message when I try to run training code:

Traceback (most recent call last):
Traceback (most recent call last):
  File "main.py", line 20, in <module>
  File "main.py", line 20, in <module>
    from models_inpaint import InpaintingModel
  File "/media/caig/新增磁碟區/SPL/models_inpaint.py", line 9, in <module>
    from models_inpaint import InpaintingModel
  File "/media/caig/新增磁碟區/SPL/models_inpaint.py", line 9, in <module>
    from src.models import create_model
  File "/media/caig/新增磁碟區/SPL/src/models/__init__.py", line 1, in <module>
    from src.models import create_model
  File "/media/caig/新增磁碟區/SPL/src/models/__init__.py", line 1, in <module>
    from .utils import create_model
  File "/media/caig/新增磁碟區/SPL/src/models/utils/__init__.py", line 1, in <module>
    from .utils import create_model
  File "/media/caig/新增磁碟區/SPL/src/models/utils/__init__.py", line 1, in <module>
    from .factory import create_model
  File "/media/caig/新增磁碟區/SPL/src/models/utils/factory.py", line 5, in <module>
    from .factory import create_model
  File "/media/caig/新增磁碟區/SPL/src/models/utils/factory.py", line 5, in <module>
    from ..tresnet import TResnetM, TResnetL, TResnetXL
  File "/media/caig/新增磁碟區/SPL/src/models/tresnet/__init__.py", line 1, in <module>
    from ..tresnet import TResnetM, TResnetL, TResnetXL
  File "/media/caig/新增磁碟區/SPL/src/models/tresnet/__init__.py", line 1, in <module>
    from .tresnet import TResnetM, TResnetL, TResnetXL
  File "/media/caig/新增磁碟區/SPL/src/models/tresnet/tresnet.py", line 8, in <module>
    from .tresnet import TResnetM, TResnetL, TResnetXL
  File "/media/caig/新增磁碟區/SPL/src/models/tresnet/tresnet.py", line 8, in <module>
    from inplace_abn import InPlaceABN
  File "/media/caig/新增磁碟區/conda_envs/SPL2/lib/python3.7/site-packages/inplace_abn/__init__.py", line 1, in <module>
    from inplace_abn import InPlaceABN
  File "/media/caig/新增磁碟區/conda_envs/SPL2/lib/python3.7/site-packages/inplace_abn/__init__.py", line 1, in <module>
    from .abn import ABN, InPlaceABN, InPlaceABNSync
  File "/media/caig/新增磁碟區/conda_envs/SPL2/lib/python3.7/site-packages/inplace_abn/abn.py", line 8, in <module>
    from .abn import ABN, InPlaceABN, InPlaceABNSync
  File "/media/caig/新增磁碟區/conda_envs/SPL2/lib/python3.7/site-packages/inplace_abn/abn.py", line 8, in <module>
    from .functions import inplace_abn, inplace_abn_sync
  File "/media/caig/新增磁碟區/conda_envs/SPL2/lib/python3.7/site-packages/inplace_abn/functions.py", line 8, in <module>
    from .functions import inplace_abn, inplace_abn_sync
  File "/media/caig/新增磁碟區/conda_envs/SPL2/lib/python3.7/site-packages/inplace_abn/functions.py", line 8, in <module>
    from . import _backend
ImportError: /media/caig/新增磁碟區/conda_envs/SPL2/lib/python3.7/site-packages/inplace_abn/_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
    from . import _backend
ImportError: /media/caig/新增磁碟區/conda_envs/SPL2/lib/python3.7/site-packages/inplace_abn/_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

I have tried the following versions:
python 3.7
pytorch 1.8.0, 1.7.1, 1.7.0, 1.6.0
cuda 10.2, 11.1
gcc 7.5

I think it may because I use the wrong cuda version, can you tell me which version you install?
Thanks for your help!!

**Comment by WendongZh** [comment]
Wow, I have never seen this kind of problem.

I can just provide my environment as follow:
1) cuda/10.1.243-gcc-4.8.5
    cudnn/7.6.5.32-10.1-linux-x64-gcc-4.8.5
    pytorch1.7

2) cuda 11.1
    pytorch1.8.0 with py3.7_cuda11.1_cudnn8.0.5_0

Maybe you can change your cuda?  Good luck for you!

**Comment by ericdai713** [comment]
Thanks for your reply, I had tried it but it doesn't work.
Would it because I use conda environment?

**Comment by WendongZh** [comment]
Nope, I also use the conda environment and it work in at least two different environments.

What about using different installation ways for the Inplace-Abn module?

**Comment by ericdai713** [comment]
I have tried two different ways to install Inplace_ABN(pip and setup install), but it still doesn't work.

**Comment by ericdai713** [comment]
> Nope, I also use the conda environment and it work in at least two different environments.
> 
> 
> 
> What about using different installation ways for the Inplace-Abn module?

Did you use conda install to install packages?

**Comment by WendongZh** [comment]
Yes, I also use miniconda3 to install main packages including pytorch, cuda, torchvision, cudnn and others.

I remember I just use pip to install some extra packages such as opencv, pyyaml.

I have uploaded the requirement file from one of my conda environment in the project named "[requirements_conda.txt](https://github.com/WendongZh/SPL/blob/main/requirements_conda.txt)". Hope it may help.

Besides, do your other conda environments work well, I mean only this environment fails?

**Comment by ericdai713** [comment]
Thanks for your help, I will try it again.
Yes, my other conda environments work well, I think the error is caused by inplace_abn.

**Comment by ericdai713** [comment]
Hi, I tried conda create --name env --file
But I can't install some packages(The following packages are not available from current channels), can you tell me your conda version? Thank you.

**Comment by ericdai713** [comment]
I found that I can't install inplace_abn by python setup.py install, it will generate error message:
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 74, in <module>
    cmdclass={"build_ext": BuildExtension},
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 482, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1238, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/media/caig/新增磁碟區/conda_envs/SPL/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

It may because the improper cuda version, but I use the same version as the other people who installed it successfully.
Can you tell me what version shows when you do nvcc -V?
Do you have any suggestions? Thank you.

**Comment by WendongZh** [comment]
I use the Python 3.7 | Miniconda3 Linux 64-bit package to install my miniconda directly from its [homepage](https://docs.conda.io/en/latest/miniconda.html). But I don't think it matters.

About nvcc, it prints as follows:
Cuda compilation tools, release 11.4, V11.4.48
Build cuda_11.4.r11.4/compiler.30033411_0

What about using another directory without any Chinese characters? Haha, I'm not sure.

**Comment by WendongZh** [comment]
I use the Python 3.7 | Miniconda3 Linux 64-bit package to install my miniconda directly from its [homepage](https://docs.conda.io/en/latest/miniconda.html). But I don't think it matters.

About nvcc, it prints as follows:
Cuda compilation tools, release 11.4, V11.4.48
Build cuda_11.4.r11.4/compiler.30033411_0

What about using another directory without any Chinese characters? Haha, I'm not sure.

**Comment by ericdai713** [comment]
The version from https://github.com/mapillary/inplace_abn is 1.1.0, but the version in your requirements_conda.txt is 1.1.1
Can you tell me which way did you install inplace-abn module? Thank you.

**Comment by WendongZh** [comment]
For the environment I provided, I use the git command they provide:

git clone https://github.com/mapillary/inplace_abn.git
cd inplace_abn
python setup.py install

**Comment by ericdai713** [comment]
Thank you for your reply, but their version is 1.1.0 now. Maybe they changed something so that I can't install it correctly?

**Comment by WendongZh** [comment]
Emm, it seems the inplace-abn module is really a tough guy.

Since you can remove the ASL model during the testing part, it will not affect you testing our model.

If you want to train our model on your own dataset, I suggest you replace the ASL model with ResNet50 pretrained on ImageNet dataset. In this case, you need change the channel numbers of the distillation head (I remember change from 152 to 512, still useing the 64x64 size feature map extracted from 512x512 images). The performance will drop a little.

In our ablation part, we also show that pretrained detection model (yolov5) also achieves comparable performance. We use the feature map with 64x64 size directly before the regression head. So you can have a try for it but it is more complicated. You can also leave a email for me and I will send the code for you. But I'm a little busy now and I'm not sure when I have the time for it.

**Comment by ericdai713** [comment]
Thanks for your help!
I want to train on my own dataset, so can you give me the code you mentioned? Thank you so much.
This is my email
ericdai713@gmail.com

**Comment by WendongZh** [comment]
I have send the email to the provided address.

Thanks for your interests!

**Comment by ericdai713** [comment]
I will try it,
Thank you very much!!!
